apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - './infrastructure/k8s/*'
build:
  local:
    push: false
  artifacts:
    - image: raoadeelnasir/authentication
      context: authentications
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*ts'
    - image: raoadeelnasir/product
      context: products
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*ts'
