apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: raoadeelnasir/product
          env:
            - name: MONGO_URI
              value: 'mongodb://product-mongo-srv:27017/product'
            - name: NATS_CLUSTER_ID
              value: auth
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: product-srv
spec:
  selector:
    app: product
  ports:
    - port: 3000
      targetPort: 3000
      name: product
      protocol: TCP
